### ISSUE TITLE
PopcornFX libs do not compile in Release config

### ISSUE THREAD

**Issue by TheOneAbis** [PopcornFX/O3DEPopcornFXPlugin#66]
Upon attempting to build a game executable in O3DE with the popcornfx gem enabled, I get a lot of linker errors, as shown below:

![image](https://github.com/PopcornFX/O3DEPopcornFXPlugin/assets/26350896/09180eec-5a4c-46c7-b61d-6d751ebdbc05)

These errors occur because PK_RETAIL is not defined in release mode when it should be. Inside of the code CMakeLists.txt, adding this genex should fix the issue:

set(PFX_COMPILE_DEFINITIONS
    $<IF:$<CONFIG:Release>, PK_RETAIL,>
)

and then adding it under COMPILE_DEFINITIONS in the PopcornFX.Static target:

COMPILE_DEFINITIONS
        PUBLIC
            ${PFX_COMPILE_DEFINITIONS}

**Comment by ValPKFX** [comment]
Normally this should be defined in the `FindPopcornFX.cmake` in the PopcornFX package.
But indeed, it is correctly defined in the linux package but missing from the windows package.
This will be fixed in the next releases (2.15.13 and 2.17.4) and in the meantime I will merge your PR in development.
Thank you!
