### ISSUE TITLE
Is it compatible with O3DE 2305.x release build?

### ISSUE THREAD

**Issue by ohmaya** [PopcornFX/O3DEPopcornFXPlugin#69]
O3DE already has 2 "2305" releases.

However, 2305 is not listed for v2.17.4 or v2.17.3:
- Version: v2.17.4
- O3DE: 21.11, 21.11.2, 22.05.0, 22.10.0, 23.03.0
- Version: v2.17.3
- O3DE: 21.11, 21.11.2, 22.05.0, 22.10.0, 23.03.0

And, what is 23.03? Not listed here: https://github.com/o3de/o3de/releases.

v2.17.4 says "Fixed #12799: O3DE: Gem fails compilation in release configuration on Linux", it seems also fixing for me on Windows. But I still need to dismiss LogBakerMessages to build. When launching:
- Official O3DE at d63c217 (20230914, Merge pull request #16679 from aws-lumberyard-dev/gadams3/smc_and_mc_asset_browser_file_type_filters)
  - "Symbol file not loaded" or silently crashes.
  - Or sometimes it works. (**Always works in recent tries.**)
  - (Not an issue of PopcornFX) Restore Default Layout 
    - "No importable file types were detected. This likely means an internal error has taken place which has broken the "
"registration of valid import types (e.g. FBX). This type of issue requires engineering support."

Thanks.

**Comment by ValPKFX** [comment]
The gem is compatible with both versions of 2305.
The 23.03 was a typo, thank you for reporting it.
I've updated the readme and kept only 23.05 since we will focus on this version and the next 23.10.

There was indeed issues in release for both linux and windows but they should be fixed now.

Is it crashing in the PopcornFX gem?
It seems the commit d63c217 is on the development branch and not the main 2305.1, maybe there is new issues.
I will retry with this commit and keep you informed.

**Comment by ohmaya** [comment]
Now I don't see an issue in PopcornFX integration.

**Comment by ValPKFX** [comment]
Oh it was in the Builders target.
I only tried to build the GameLauncher in release, not the Editor.
Didn't know it was still compiling it even with the `if(PAL_TRAIT_BUILD_HOST_TOOLS)` in the CMakeLists.txt.
Especially since in release there is no asset processor so it shouldn't use this target.
Anyway, I've added your fix on the development branch and it will be released in next patches.
Thank you!
